'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FrontDesk.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to نوع.
        '''</summary>
        Public ReadOnly Property Lang_AR_0() As String
            Get
                Return ResourceManager.GetString("Lang_AR_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Type.
        '''</summary>
        Public ReadOnly Property Lang_EN_0() As String
            Get
                Return ResourceManager.GetString("Lang_EN_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name.
        '''</summary>
        Public ReadOnly Property Lang_EN_1() As String
            Get
                Return ResourceManager.GetString("Lang_EN_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Get Information.
        '''</summary>
        Public ReadOnly Property Lang_EN_10() As String
            Get
                Return ResourceManager.GetString("Lang_EN_10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enquiry List.
        '''</summary>
        Public ReadOnly Property Lang_EN_11() As String
            Get
                Return ResourceManager.GetString("Lang_EN_11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Visitors / Interviewees List.
        '''</summary>
        Public ReadOnly Property Lang_EN_12() As String
            Get
                Return ResourceManager.GetString("Lang_EN_12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contacts List.
        '''</summary>
        Public ReadOnly Property Lang_EN_13() As String
            Get
                Return ResourceManager.GetString("Lang_EN_13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Statistical Report.
        '''</summary>
        Public ReadOnly Property Lang_EN_14() As String
            Get
                Return ResourceManager.GetString("Lang_EN_14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Settings.
        '''</summary>
        Public ReadOnly Property Lang_EN_15() As String
            Get
                Return ResourceManager.GetString("Lang_EN_15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change Appearance.
        '''</summary>
        Public ReadOnly Property Lang_EN_16() As String
            Get
                Return ResourceManager.GetString("Lang_EN_16", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Language.
        '''</summary>
        Public ReadOnly Property Lang_EN_17() As String
            Get
                Return ResourceManager.GetString("Lang_EN_17", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your Company Information.
        '''</summary>
        Public ReadOnly Property Lang_EN_18() As String
            Get
                Return ResourceManager.GetString("Lang_EN_18", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to About Software.
        '''</summary>
        Public ReadOnly Property Lang_EN_19() As String
            Get
                Return ResourceManager.GetString("Lang_EN_19", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email.
        '''</summary>
        Public ReadOnly Property Lang_EN_2() As String
            Get
                Return ResourceManager.GetString("Lang_EN_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exit.
        '''</summary>
        Public ReadOnly Property Lang_EN_20() As String
            Get
                Return ResourceManager.GetString("Lang_EN_20", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Phone.
        '''</summary>
        Public ReadOnly Property Lang_EN_3() As String
            Get
                Return ResourceManager.GetString("Lang_EN_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Other Contact Details.
        '''</summary>
        Public ReadOnly Property Lang_EN_4() As String
            Get
                Return ResourceManager.GetString("Lang_EN_4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Description.
        '''</summary>
        Public ReadOnly Property Lang_EN_5() As String
            Get
                Return ResourceManager.GetString("Lang_EN_5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ID #.
        '''</summary>
        Public ReadOnly Property Lang_EN_6() As String
            Get
                Return ResourceManager.GetString("Lang_EN_6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date / Time.
        '''</summary>
        Public ReadOnly Property Lang_EN_7() As String
            Get
                Return ResourceManager.GetString("Lang_EN_7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Submit.
        '''</summary>
        Public ReadOnly Property Lang_EN_8() As String
            Get
                Return ResourceManager.GetString("Lang_EN_8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Welcome To Front Desk!.
        '''</summary>
        Public ReadOnly Property Lang_EN_9() As String
            Get
                Return ResourceManager.GetString("Lang_EN_9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        '''&lt;language&gt;
        '''  &lt;selected&gt;EN&lt;/selected&gt;
        '''&lt;/language&gt;
        '''&lt;!-- ashumeow --&gt;.
        '''</summary>
        Public ReadOnly Property show_lang() As String
            Get
                Return ResourceManager.GetString("show_lang", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
